import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "잔디농장",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <NavBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
