import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "잔디농장",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
